### ISSUE TITLE
Mention on reddit and/or hackernews

### ISSUE THREAD

**Issue by JdeH** [Michael-F-Ellis/NearlyPurePythonWebAppDemo#4]
Hi Michael

I'd like to mention your demo on reddit and/or hackernews,
to illustrate the possibility of (nearly) pure Python development.
Is that alright for you?
Or would you prefer to do that yourself?
Or not at all?

Also maybe it would be nice if it were pip-installable from PyPi, since that may lower the threshold.

Kind regards
Jacques de Hooge

**Comment by Michael-F-Ellis** [comment]
Hi Jacques,
It's more than all right. Thanks very much! I suspect a mention from you will carry far more weight than one from me.

I've never tried packaging and submitting anything to PyPi.  Is there a useful guide somewhere? It's not likely to happen soon unless its very easy.  I'm leaving next Thursday for a 3-week choral tour in Europe (Prague, Brno, Vienna, Saltzburg) and between now and then I've got some obligations to fulfill for  a client.

Speaking of client work, I'm happy to say  I've just shown the same client an early version of a control system with a web interface built around the skeleton of the demo.  It's part of a process controller for an industrial humidity control system and written entirely in Python with multiple processes communicating with each other with pyzeromq and with hardware over pymodbus.  It's running nicely on a Raspberry Pi 3.

Being able to write the browser client entirely in Python was, for me, a huge win.  I've now got a much better feeling that the combination of generating JS with  Transcrypt  and HTML+CSS with my htmltree.Element() "anti-parser" class is viable for non-trivial applications.

**Comment by pierrejean-coudert** [comment]
Just a proposition: Why not add this demo to the Transcrypt repository (keeping a reference to the original repository) ? This way it will be directly installed along with Transcrypt and will benefit to more people.

**Comment by Michael-F-Ellis** [comment]
@pierrejean-coudert, I've no objection and would feel honored if Jacques wants to include it.

**Comment by JdeH** [comment]
Yes, I'd certainly want to include this somehow.
Only looking for the best way to do so.
On GitHub it could probably be included it as a subproject.
In that way it would remain up to date, as opposed to a copy.

But I'd also like it to be available on PyPi.
The simplest way indeed may be to make it part of the Transcrypt download.
One problem I have with that is that it would create a depencendy on Bottle.
I'd like to keep dependencies to a minimum.
So maybe it'd better be separate there.
Also psychologically the availability of a "framework for Transcrypt" may be advantageous.
It's more than just a demo.
However minimalistic, I think it has potential (or maybe even because it's minimalistic).

So, still thinking about this one in a practical sense...

It pleases me to hear that you (Michael) are already using it for a  practical project.
If you ever encounter something that you can share information / screenshots about and can be used as a showcase, let me know, since the "gallery" is still very meager.
Somewhat frustrating since I know of several very serious, even mission criticial, applications.
But they are all non-public.

@Michael-F-Ellis : Hope you like it in Europe! Many of my family members also are in a choir, e.g. my wife. I've tried once, but find it quite hard to remember my (tenor) line...

**Comment by Michael-F-Ellis** [comment]
Thanks, Jacques.  I've also been trying to decide if it's really a fit for PyPi.  I usually think of using pip install for libraries and applications, but the demo aims at being a skeleton someone can clone and flesh out for their own application.  So maybe GitHub is the best home for it.  

I suppose htmltree.py could stand on its own as a separate library module that can be used in both client and server to generate HTML & CSS, but it's really quite a tiny little thing with just the single Element() class.  I'm trying to resist the temptation to add  subclasses for every possible tag.  It's something users can easily do for themselves and bake in whatever defaults suit the application.  

I wish I could share the app I'm working on but it's a work for hire that runs locally on a product installed in factories and warehouses.  If I can ever get back to being retired there a several music projects I want to put up for public use and I'll certainly be making use of Transcrypt and the demo skeleton.

I'm looking forward to the trip.  We get to London a couple of times a year to visit our daughter and granddaughter, but it's been more than 10 years since either my wife or myself have been on the Continent and neither of us have visited the Austria or the Czech Republic.
